"""empty message

Revision ID: 81e143d55659
Revises: 72937280d634
Create Date: 2024-01-10 08:32:37.668858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e143d55659'
down_revision = '72937280d634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('messages', 'messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('messages', sa.VARCHAR(), nullable=True))
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###
